/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package college_fee_management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell
 */
public class EditCourse extends javax.swing.JFrame {

    /** Creates new form EditCourse */
    DefaultTableModel model;
    public EditCourse() {
        initComponents();
        setRecordsToTable();
    }
    public void setRecordsToTable(){
try{
    Connection con =DBConnection.getConnection();
    PreparedStatement pst =con.prepareStatement("select * from course");
    ResultSet rs =pst.executeQuery();
    
    while(rs.next()){
        
    String courseId =rs.getString("Id");
    String cname =rs.getString("cname");
    String cost =rs.getString("cost");
    
    
    Object[] obj = {courseId,cname,cost};
    model=(DefaultTableModel)tbl_courseData.getModel();
    model.addRow(obj);
    }

}catch(Exception e){
   e.printStackTrace();
    }
}
    public void clearTable(){
    DefaultTableModel model =(DefaultTableModel)tbl_courseData.getModel();
    model.setRowCount(0);
    }
public void addCourse (int id, String cname,double cost){

    try{
    Connection con = DBConnection.getConnection();
    PreparedStatement pst =con.prepareStatement("insert into course values(?,?,?)");
    pst.setInt(1, id);
    pst.setString(2, cname);
    pst.setDouble(3, cost);
    int rowCount = pst.executeUpdate();
    if(rowCount==1){
        JOptionPane.showMessageDialog(this, "Course Added Succesfully");
        clearTable();
        setRecordsToTable();
    }else{
        JOptionPane.showMessageDialog(this,"Course Insertion Failed");
    }  
    }
catch(Exception e){
    JOptionPane.showMessageDialog(this,"Course Insertion Failed");
e.printStackTrace();
}
}
  public void update(int id,String cname,double cost) {
  try{
    Connection con = DBConnection.getConnection();
    PreparedStatement pst = con.prepareStatement("update course set cname =?,cost=? where id = ?");
    pst.setString(1, cname);
    pst.setDouble(2, cost);
    pst.setInt(3, id);
    int rowCount = pst.executeUpdate();
    if(rowCount==1){
        JOptionPane.showMessageDialog(this, "Course Updated Succesfully");
        clearTable();
        setRecordsToTable();
    }else{
        JOptionPane.showMessageDialog(this,"Course Updation Failed");
    }  
    }
catch(Exception e){
    JOptionPane.showMessageDialog(this,"Course Updation Failed");
e.printStackTrace();
}
 } 
  public void delete(int id) {
  try{
    Connection con = DBConnection.getConnection();
    PreparedStatement pst = con.prepareStatement("delete from  course where id = ?");
    pst.setInt(1, id);
    int rowCount = pst.executeUpdate();
    if(rowCount==1){
        JOptionPane.showMessageDialog(this, "Course Deleted Succesfully");
        clearTable();
        setRecordsToTable();
    }else{
        JOptionPane.showMessageDialog(this,"Course Deletion Failed");
    }  
    }
catch(Exception e){
    JOptionPane.showMessageDialog(this,"Course Deletion Failed");
e.printStackTrace();
}
 } 
    
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_addcourse = new javax.swing.JButton();
        btn_updatecourse = new javax.swing.JButton();
        txt_courseCost = new javax.swing.JTextField();
        txt_courseId = new javax.swing.JTextField();
        txt_courseName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_courseData = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        panelsideBar = new javax.swing.JPanel();
        panelHome5 = new javax.swing.JPanel();
        btnhome5 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        panelHome1 = new javax.swing.JPanel();
        btnhome1 = new javax.swing.JLabel();
        panelHome2 = new javax.swing.JPanel();
        btnhome2 = new javax.swing.JLabel();
        panelHome3 = new javax.swing.JPanel();
        btnhome3 = new javax.swing.JLabel();
        panelHome6 = new javax.swing.JPanel();
        btnhome6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course Cost :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Id :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Couse Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));

        btn_delete.setBackground(new java.awt.Color(51, 51, 51));
        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, -1, -1));

        btn_addcourse.setBackground(new java.awt.Color(51, 51, 51));
        btn_addcourse.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btn_addcourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_addcourse.setText("ADD");
        btn_addcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcourseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 750, 70, 30));

        btn_updatecourse.setBackground(new java.awt.Color(51, 51, 51));
        btn_updatecourse.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btn_updatecourse.setForeground(new java.awt.Color(255, 255, 255));
        btn_updatecourse.setText("UPDATE");
        btn_updatecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatecourseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_updatecourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, -1, -1));

        txt_courseCost.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel1.add(txt_courseCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 190, -1));

        txt_courseId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_courseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_courseIdActionPerformed(evt);
            }
        });
        jPanel1.add(txt_courseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 190, -1));

        txt_courseName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txt_courseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_courseNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 190, -1));

        tbl_courseData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_courseData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Course Price"
            }
        ));
        tbl_courseData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_courseDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_courseData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 600, 810));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EDIT COURSE DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 580, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/back-button.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome5.setBackground(new java.awt.Color(0, 102, 102));
        panelHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome5.setForeground(new java.awt.Color(255, 255, 255));
        panelHome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome5.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome5.setForeground(new java.awt.Color(255, 255, 255));
        btnhome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/back-button.png"))); // NOI18N
        btnhome5.setText("Back");
        btnhome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome5MouseExited(evt);
            }
        });
        panelHome5.add(btnhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, -1));

        panelsideBar.add(panelHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 330, 70));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome.setText("  Logout");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        panelHome.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome1.setBackground(new java.awt.Color(0, 102, 102));
        panelHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome1.setForeground(new java.awt.Color(255, 255, 255));
        panelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome1.setForeground(new java.awt.Color(255, 255, 255));
        btnhome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/home.png"))); // NOI18N
        btnhome1.setText("HOME");
        btnhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome1MouseExited(evt);
            }
        });
        panelHome1.add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 280, -1));

        panelsideBar.add(panelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 330, 70));

        panelHome2.setBackground(new java.awt.Color(0, 102, 102));
        panelHome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome2.setForeground(new java.awt.Color(255, 255, 255));
        panelHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome2.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome2.setForeground(new java.awt.Color(255, 255, 255));
        btnhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/search2.png"))); // NOI18N
        btnhome2.setText("Search Record");
        btnhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome2MouseExited(evt);
            }
        });
        panelHome2.add(btnhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, -1));

        panelsideBar.add(panelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 330, 70));

        panelHome3.setBackground(new java.awt.Color(0, 102, 102));
        panelHome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome3.setForeground(new java.awt.Color(255, 255, 255));
        panelHome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome3.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome3.setForeground(new java.awt.Color(255, 255, 255));
        btnhome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/new-user.png"))); // NOI18N
        btnhome3.setText("New Registration");
        btnhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome3MouseExited(evt);
            }
        });
        panelHome3.add(btnhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, -1));

        panelsideBar.add(panelHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 330, 70));

        panelHome6.setBackground(new java.awt.Color(0, 102, 102));
        panelHome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome6.setForeground(new java.awt.Color(255, 255, 255));
        panelHome6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome6.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome6.setForeground(new java.awt.Color(255, 255, 255));
        btnhome6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/view all record.png"))); // NOI18N
        btnhome6.setText("View All Record");
        btnhome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome6MouseExited(evt);
            }
        });
        panelHome6.add(btnhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, -1));

        panelsideBar.add(panelHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 330, 70));

        jPanel1.add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 80, 520, 820));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1960, 1000));

        setSize(new java.awt.Dimension(1914, 1039));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_courseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_courseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_courseNameActionPerformed

    private void btn_updatecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatecourseActionPerformed
       int id = Integer.parseInt(txt_courseId.getText());
       String cname = txt_courseName.getText();
       double cost = Double.parseDouble(txt_courseCost.getText());
       update(id,cname,cost);
    }//GEN-LAST:event_btn_updatecourseActionPerformed

    private void btn_addcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcourseActionPerformed
       int id = Integer.parseInt(txt_courseId.getText());
       String cname = txt_courseName.getText();
       double cost = Double.parseDouble(txt_courseCost.getText());
       addCourse(id,cname,cost);
    }//GEN-LAST:event_btn_addcourseActionPerformed

    private void btnhome5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseClicked
Home a=new Home();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnhome5MouseClicked

    private void btnhome5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseEntered
        Color clr=new Color(0,153,153);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btnhome5MouseEntered

    private void btnhome5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseExited
        Color clr=new Color(0,102,102);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btnhome5MouseExited

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        Color clr=new Color(0,102,102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseExited

    private void btnhome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseEntered
        Color clr=new Color(0,153,153);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btnhome1MouseEntered

    private void btnhome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseExited
        Color clr=new Color(0,102,102);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btnhome1MouseExited

    private void btnhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseClicked
        SearchRecord a=new SearchRecord();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhome2MouseClicked

    private void btnhome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseEntered
        Color clr=new Color(0,153,153);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btnhome2MouseEntered

    private void btnhome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseExited
        Color clr=new Color(0,102,102);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btnhome2MouseExited

    private void btnhome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseClicked
       AddFees addFees=new AddFees();
 addFees.setVisible(true);
 this.dispose();
                       
    }//GEN-LAST:event_btnhome3MouseClicked

    private void btnhome3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseEntered
        Color clr=new Color(0,153,153);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btnhome3MouseEntered

    private void btnhome3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseExited
        Color clr=new Color(0,102,102);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btnhome3MouseExited

    private void btnhome6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseClicked
        ViewAllRecord a=new ViewAllRecord();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome6MouseClicked

    private void btnhome6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseEntered
        Color clr=new Color(0,153,153);
        panelHome6.setBackground(clr);
    }//GEN-LAST:event_btnhome6MouseEntered

    private void btnhome6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseExited
        Color clr=new Color(0,102,102);
        panelHome6.setBackground(clr);
    }//GEN-LAST:event_btnhome6MouseExited

    private void tbl_courseDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_courseDataMouseClicked
       int rowNo =tbl_courseData.getSelectedRow();
       TableModel model = tbl_courseData.getModel();
       txt_courseId.setText(model.getValueAt(rowNo,0).toString());
              txt_courseName.setText(model.getValueAt(rowNo,1).toString());
       txt_courseCost.setText(model.getValueAt(rowNo,2).toString());

    }//GEN-LAST:event_tbl_courseDataMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
      int id = Integer.parseInt(txt_courseId.getText());
       delete(id);
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_courseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_courseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_courseIdActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
   Home a=new Home();
   a.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnhome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseClicked
Home home = new Home();
    home.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcourse;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_updatecourse;
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnhome1;
    private javax.swing.JLabel btnhome2;
    private javax.swing.JLabel btnhome3;
    private javax.swing.JLabel btnhome5;
    private javax.swing.JLabel btnhome6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome1;
    private javax.swing.JPanel panelHome2;
    private javax.swing.JPanel panelHome3;
    private javax.swing.JPanel panelHome5;
    private javax.swing.JPanel panelHome6;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTable tbl_courseData;
    private javax.swing.JTextField txt_courseCost;
    private javax.swing.JTextField txt_courseId;
    private javax.swing.JTextField txt_courseName;
    // End of variables declaration//GEN-END:variables

}
