/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_fee_management;


import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Dell
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        getRecords();
        Container c =getContentPane();
        c.setBackground(new Color (0,153,153));
    }
public void getRecords(){
    try {
    Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("select * from fees_Details order by reciept_no desc fetch first 1 rows only");
        ResultSet rs = pst.executeQuery();
        rs.next();
        txt_receiptNo.setText(rs.getString("reciept_no"));
        txt_paymentmode.setText(rs.getString("payment_mode"));
        
        String paymentMode = rs.getString("payment_mode");
        
        if (paymentMode.equalsIgnoreCase("cash")){
            lbl_cheque_dd.setText("Cheque No");
            txt_cheque_dd.setText("-");
            txt_bankName.setText("-");
        }
       if (paymentMode.equalsIgnoreCase("cheque")){
            lbl_cheque_dd.setText("Cheque No :");
            txt_cheque_dd.setText(rs.getString("cheque_no"));
            txt_bankName.setText(rs.getString("bank_name"));
        }
        if (paymentMode.equalsIgnoreCase("dd")){
            lbl_cheque_dd.setText("DD No :");
            txt_cheque_dd.setText(rs.getString("dd_no"));
            txt_bankName.setText(rs.getString("bank_name"));
        }
        if (paymentMode.equalsIgnoreCase("Card")){
            lbl_cheque_dd.setText("Cheque No");
            txt_cheque_dd.setText("-");
            txt_bankName.setText(rs.getString("bank_name"));
        }
        txt_receivedFrom.setText(rs.getString("student_name"));
        txt_date.setText(rs.getString("date"));
         txt_year1.setText(rs.getString("year1"));
         txt_year2.setText(rs.getString("year2"));
         txt_rollno.setText(rs.getString("roll_no"));
        txt_amount.setText(rs.getString("amount"));
        txt_total.setText(rs.getString("total_amount"));
        txt_totalinwords.setText(rs.getString("total_in_words"));
        txt_coursename.setText(rs.getString("course_name"));
          }catch (Exception e){
             e.printStackTrace();
             }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome5 = new javax.swing.JPanel();
        btn_back = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btn_edit = new javax.swing.JLabel();
        panelHome7 = new javax.swing.JPanel();
        btnhome7 = new javax.swing.JLabel();
        panelHome8 = new javax.swing.JPanel();
        btnhome8 = new javax.swing.JLabel();
        panelHome9 = new javax.swing.JPanel();
        btnhome9 = new javax.swing.JLabel();
        panelHome1 = new javax.swing.JPanel();
        btn_home = new javax.swing.JLabel();
        panelHome2 = new javax.swing.JPanel();
        btn_search_record = new javax.swing.JLabel();
        panelHome3 = new javax.swing.JPanel();
        btn_edit_course = new javax.swing.JLabel();
        panelHome6 = new javax.swing.JPanel();
        btn_view_record = new javax.swing.JLabel();
        panelHome10 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        panelHome11 = new javax.swing.JPanel();
        btnhome11 = new javax.swing.JLabel();
        panelHome12 = new javax.swing.JPanel();
        btnhome12 = new javax.swing.JLabel();
        panelHome13 = new javax.swing.JPanel();
        btnhome13 = new javax.swing.JLabel();
        panelHome14 = new javax.swing.JPanel();
        btn_print = new javax.swing.JLabel();
        panelHome15 = new javax.swing.JPanel();
        btnhome15 = new javax.swing.JLabel();
        panelHome16 = new javax.swing.JPanel();
        btnhome16 = new javax.swing.JLabel();
        panelHome17 = new javax.swing.JPanel();
        btnhome17 = new javax.swing.JLabel();
        panel_print = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_receiptNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        txt_bankName = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        lbl_bankname = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_cheque_dd = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txt_total = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_totalinwords = new javax.swing.JLabel();
        txt_receivedFrom = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_rollno = new javax.swing.JLabel();
        txt_year1 = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_amount = new javax.swing.JLabel();
        txt_coursename = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome5.setBackground(new java.awt.Color(0, 102, 102));
        panelHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome5.setForeground(new java.awt.Color(255, 255, 255));
        panelHome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/back-button.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        panelHome5.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, -1));

        panelsideBar.add(panelHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 330, 70));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/edit2.png"))); // NOI18N
        btn_edit.setText("  Edit");
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        panelHome.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome7.setBackground(new java.awt.Color(0, 102, 102));
        panelHome7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome7.setForeground(new java.awt.Color(255, 255, 255));
        panelHome7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome7.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome7.setForeground(new java.awt.Color(255, 255, 255));
        btnhome7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome7.setText("  Logout");
        btnhome7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome7MouseExited(evt);
            }
        });
        panelHome7.add(btnhome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome.add(panelHome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome8.setBackground(new java.awt.Color(0, 102, 102));
        panelHome8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome8.setForeground(new java.awt.Color(255, 255, 255));
        panelHome8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome8.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome8.setForeground(new java.awt.Color(255, 255, 255));
        btnhome8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome8.setText("  Logout");
        btnhome8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome8MouseExited(evt);
            }
        });
        panelHome8.add(btnhome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome9.setBackground(new java.awt.Color(0, 102, 102));
        panelHome9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome9.setForeground(new java.awt.Color(255, 255, 255));
        panelHome9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome9.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome9.setForeground(new java.awt.Color(255, 255, 255));
        btnhome9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome9.setText("  Logout");
        btnhome9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome9MouseExited(evt);
            }
        });
        panelHome9.add(btnhome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome8.add(panelHome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome.add(panelHome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 910, 330, 70));

        panelHome1.setBackground(new java.awt.Color(0, 102, 102));
        panelHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome1.setForeground(new java.awt.Color(255, 255, 255));
        panelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/home.png"))); // NOI18N
        btn_home.setText("  HOME");
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        panelHome1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 330, 70));

        panelHome2.setBackground(new java.awt.Color(0, 102, 102));
        panelHome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome2.setForeground(new java.awt.Color(255, 255, 255));
        panelHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_search_record.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_search_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_search_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/search2.png"))); // NOI18N
        btn_search_record.setText("Search Record");
        btn_search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseExited(evt);
            }
        });
        panelHome2.add(btn_search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, -1));

        panelsideBar.add(panelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 330, 70));

        panelHome3.setBackground(new java.awt.Color(0, 102, 102));
        panelHome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome3.setForeground(new java.awt.Color(255, 255, 255));
        panelHome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_edit_course.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_edit_course.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/edit2.png"))); // NOI18N
        btn_edit_course.setText("Edit Course");
        btn_edit_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseExited(evt);
            }
        });
        panelHome3.add(btn_edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, -1));

        panelsideBar.add(panelHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 330, 70));

        panelHome6.setBackground(new java.awt.Color(0, 102, 102));
        panelHome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome6.setForeground(new java.awt.Color(255, 255, 255));
        panelHome6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_view_record.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_view_record.setForeground(new java.awt.Color(255, 255, 255));
        btn_view_record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/view all record.png"))); // NOI18N
        btn_view_record.setText("View All Record");
        btn_view_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view_recordMouseExited(evt);
            }
        });
        panelHome6.add(btn_view_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, -1));

        panelsideBar.add(panelHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 330, 70));

        panelHome10.setBackground(new java.awt.Color(0, 102, 102));
        panelHome10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome10.setForeground(new java.awt.Color(255, 255, 255));
        panelHome10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btn_logout.setText("  Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        panelHome10.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome11.setBackground(new java.awt.Color(0, 102, 102));
        panelHome11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome11.setForeground(new java.awt.Color(255, 255, 255));
        panelHome11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome11.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome11.setForeground(new java.awt.Color(255, 255, 255));
        btnhome11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome11.setText("  Logout");
        btnhome11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome11MouseExited(evt);
            }
        });
        panelHome11.add(btnhome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome10.add(panelHome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome12.setBackground(new java.awt.Color(0, 102, 102));
        panelHome12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome12.setForeground(new java.awt.Color(255, 255, 255));
        panelHome12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome12.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome12.setForeground(new java.awt.Color(255, 255, 255));
        btnhome12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome12.setText("  Logout");
        btnhome12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome12MouseExited(evt);
            }
        });
        panelHome12.add(btnhome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome13.setBackground(new java.awt.Color(0, 102, 102));
        panelHome13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome13.setForeground(new java.awt.Color(255, 255, 255));
        panelHome13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome13.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome13.setForeground(new java.awt.Color(255, 255, 255));
        btnhome13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome13.setText("  Logout");
        btnhome13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome13MouseExited(evt);
            }
        });
        panelHome13.add(btnhome13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome12.add(panelHome13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome10.add(panelHome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelsideBar.add(panelHome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 330, 70));

        panelHome14.setBackground(new java.awt.Color(0, 102, 102));
        panelHome14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome14.setForeground(new java.awt.Color(255, 255, 255));
        panelHome14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_print.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/printer-.png"))); // NOI18N
        btn_print.setText("  Print");
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        panelHome14.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome15.setBackground(new java.awt.Color(0, 102, 102));
        panelHome15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome15.setForeground(new java.awt.Color(255, 255, 255));
        panelHome15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome15.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome15.setForeground(new java.awt.Color(255, 255, 255));
        btnhome15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome15.setText("  Logout");
        btnhome15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome15MouseExited(evt);
            }
        });
        panelHome15.add(btnhome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome14.add(panelHome15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome16.setBackground(new java.awt.Color(0, 102, 102));
        panelHome16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome16.setForeground(new java.awt.Color(255, 255, 255));
        panelHome16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome16.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome16.setForeground(new java.awt.Color(255, 255, 255));
        btnhome16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome16.setText("  Logout");
        btnhome16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome16MouseExited(evt);
            }
        });
        panelHome16.add(btnhome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome17.setBackground(new java.awt.Color(0, 102, 102));
        panelHome17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome17.setForeground(new java.awt.Color(255, 255, 255));
        panelHome17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome17.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome17.setForeground(new java.awt.Color(255, 255, 255));
        btnhome17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome17.setText("  Logout");
        btnhome17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome17MouseExited(evt);
            }
        });
        panelHome17.add(btnhome17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelHome16.add(panelHome17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome14.add(panelHome16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelsideBar.add(panelHome14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 790, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 1040));

        panel_print.setBackground(new java.awt.Color(255, 255, 255));
        panel_print.setForeground(new java.awt.Color(0, 0, 51));
        panel_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Tuljabhavani Seva Pratishthan's ");
        panel_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 32));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Soniya Gandhi Polytechnic,Shrigonda");
        panel_print.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 630, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("A/P - Shrigonda, Balajinagar. Tal- Shrigonda, Dist-Ahmednagar Pin-413701");
        panel_print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 450, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 1020, 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel1.setText("Enrollment No :");
        panel_print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, -1, -1));

        txt_receiptNo.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        panel_print.add(txt_receiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 50, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel3.setText("Payment Mode :");
        panel_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        txt_paymentmode.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txt_paymentmode.setText("Payment Mode");
        panel_print.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 120, 20));

        txt_bankName.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txt_bankName.setText("Bank Name");
        panel_print.add(txt_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        lbl_cheque_dd.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_cheque_dd.setText("Cheque_dd       :");
        panel_print.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        lbl_bankname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_bankname.setText("Bank Name       :");
        panel_print.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel12.setText("Received From :");
        panel_print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        txt_cheque_dd.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        panel_print.add(txt_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 100, 20));

        jLabel14.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        jLabel14.setText("1");
        panel_print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 30, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel15.setText("Reciever's Signature");
        panel_print.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 940, 170, -1));
        panel_print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1220, 30));
        panel_print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 930, 300, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel16.setText("Date :");
        panel_print.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel17.setText("Sr.No.");
        panel_print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 50, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel18.setText("Heads");
        panel_print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 50, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel19.setText("The following payment in the college office for the year");
        panel_print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 420, -1));
        panel_print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 462, 1220, 30));
        panel_print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 720, 300, 30));

        txt_total.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txt_total.setText("Total");
        panel_print.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 740, 100, 20));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel21.setText("Amount(Rs)");
        panel_print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 100, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel22.setText("Total in words  :");
        panel_print.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 730, 140, -1));

        txt_totalinwords.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txt_totalinwords.setText("Total in words");
        panel_print.add(txt_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 730, 400, 20));

        txt_receivedFrom.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txt_receivedFrom.setText("Reveived From");
        panel_print.add(txt_receivedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 280, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel26.setText("Receipt No.      :  SGP-");
        panel_print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txt_date.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        panel_print.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 120, 20));

        txt_rollno.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txt_rollno.setText("111640120");
        panel_print.add(txt_rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 120, 20));

        txt_year1.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txt_year1.setText("2022");
        panel_print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 50, 20));

        txt_year2.setFont(new java.awt.Font("Monospaced", 1, 17)); // NOI18N
        txt_year2.setText("2023");
        panel_print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 50, 20));

        lbl1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl1.setText("to");
        panel_print.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 20, -1));
        panel_print.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 462, 1220, 30));

        txt_amount.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txt_amount.setText("Amount");
        panel_print.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 100, 20));

        txt_coursename.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txt_coursename.setText("Course_name");
        panel_print.add(txt_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 230, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/sgp.png"))); // NOI18N
        panel_print.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -10, 260, 210));

        getContentPane().add(panel_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 1220, 1020));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Print Receipt");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        setSize(new java.awt.Dimension(1981, 1095));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
Home a=new Home();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        Color clr=new Color(0,153,153);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        Color clr=new Color(0,102,102);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        Color clr=new Color(0,153,153);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        Color clr=new Color(0,102,102);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_search_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseEntered
        Color clr=new Color(0,153,153);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseEntered

    private void btn_search_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseExited
        Color clr=new Color(0,102,102);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseExited

    private void btn_edit_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseEntered
        Color clr=new Color(0,153,153);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseEntered

    private void btn_edit_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseExited
        Color clr=new Color(0,102,102);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseExited

    private void btn_view_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_recordMouseEntered
        Color clr=new Color(0,153,153);
        panelHome6.setBackground(clr);
    }//GEN-LAST:event_btn_view_recordMouseEntered

    private void btn_view_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_recordMouseExited
        Color clr=new Color(0,102,102);
        panelHome6.setBackground(clr);
    }//GEN-LAST:event_btn_view_recordMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
     Color clr=new Color(0,153,153);
        panelHome10.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
       Color clr=new Color(0,102,102);
        panelHome10.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btnhome11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome11MouseEntered

    private void btnhome11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome11MouseExited

    private void btnhome12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome12MouseEntered

    private void btnhome12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome12MouseExited

    private void btnhome13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome13MouseEntered

    private void btnhome13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome13MouseExited

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
   Color clr=new Color(0,153,153);
        panelHome14.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
       Color clr=new Color(0,102,102);
        panelHome14.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btnhome15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome15MouseEntered

    private void btnhome15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome15MouseExited

    private void btnhome16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome16MouseEntered

    private void btnhome16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome16MouseExited

    private void btnhome17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome17MouseEntered

    private void btnhome17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome17MouseExited

    private void btnhome9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome9MouseExited

    private void btnhome9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome9MouseEntered

    private void btnhome8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome8MouseExited

    private void btnhome8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome8MouseEntered

    private void btnhome7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome7MouseExited

    private void btnhome7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome7MouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        Color clr=new Color(0,102,102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
      PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
UpdateFeesDetails update = new UpdateFeesDetails();
update.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_edit_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseClicked
 EditCourse a=new EditCourse();
       a.setVisible(true);
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edit_courseMouseClicked

    private void btn_view_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_recordMouseClicked
ViewAllRecord a=new ViewAllRecord();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_view_recordMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
Login_page a= new Login_page();
      a.setVisible(true);
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseClicked
SearchRecord a=new SearchRecord();
        a.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_btn_search_recordMouseClicked

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
Home home = new Home();
    home.setVisible(true);
    this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_edit_course;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel btn_search_record;
    private javax.swing.JLabel btn_view_record;
    private javax.swing.JLabel btnhome11;
    private javax.swing.JLabel btnhome12;
    private javax.swing.JLabel btnhome13;
    private javax.swing.JLabel btnhome15;
    private javax.swing.JLabel btnhome16;
    private javax.swing.JLabel btnhome17;
    private javax.swing.JLabel btnhome7;
    private javax.swing.JLabel btnhome8;
    private javax.swing.JLabel btnhome9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome1;
    private javax.swing.JPanel panelHome10;
    private javax.swing.JPanel panelHome11;
    private javax.swing.JPanel panelHome12;
    private javax.swing.JPanel panelHome13;
    private javax.swing.JPanel panelHome14;
    private javax.swing.JPanel panelHome15;
    private javax.swing.JPanel panelHome16;
    private javax.swing.JPanel panelHome17;
    private javax.swing.JPanel panelHome2;
    private javax.swing.JPanel panelHome3;
    private javax.swing.JPanel panelHome5;
    private javax.swing.JPanel panelHome6;
    private javax.swing.JPanel panelHome7;
    private javax.swing.JPanel panelHome8;
    private javax.swing.JPanel panelHome9;
    private javax.swing.JPanel panel_print;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_amount;
    private javax.swing.JLabel txt_bankName;
    private javax.swing.JLabel txt_cheque_dd;
    private javax.swing.JLabel txt_coursename;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel txt_receiptNo;
    private javax.swing.JLabel txt_receivedFrom;
    private javax.swing.JLabel txt_rollno;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_totalinwords;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
