/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_fee_management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Dell
 */


public class SearchRecord extends javax.swing.JFrame {

    /**
     * Creates new form SearchRecord
     */
    DefaultTableModel model;
    public SearchRecord() {
        initComponents();
        setRecordsToTable();
    }


public void setRecordsToTable(){
try{
    Connection con =DBConnection.getConnection();
    PreparedStatement pst =con.prepareStatement("select * from fees_details");
    ResultSet rs =pst.executeQuery();
    
    while(rs.next()){
        
    String receiptNo =rs.getString("reciept_no");
    String rollNo =rs.getString("roll_no");
    String studentName =rs.getString("student_name");
    String paymentMode =rs.getString("payment_mode");
    String courseName =rs.getString("course_name");
    float amount = rs.getFloat("total_amount");
    String remark =rs.getString("remark");
    
    Object[] obj = {receiptNo,rollNo,studentName,courseName,paymentMode,amount,remark};
    model=(DefaultTableModel)tbl_studentdata.getModel();
    model.addRow(obj);
    }

}catch(SQLException e){
    }
}
public void search(String str){
    model=(DefaultTableModel)tbl_studentdata.getModel();
    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    tbl_studentdata.setRowSorter(trs);
    trs.setRowFilter(RowFilter.regexFilter(str));
}
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fees_managementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("fees_managementPU").createEntityManager();
        feesDetailsQuery = java.beans.Beans.isDesignTime() ? null : fees_managementPUEntityManager.createQuery("SELECT f FROM FeesDetails f");
        feesDetailsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : feesDetailsQuery.getResultList();
        panelsideBar = new javax.swing.JPanel();
        panelHome5 = new javax.swing.JPanel();
        btnhome5 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        panelHome1 = new javax.swing.JPanel();
        btnhome1 = new javax.swing.JLabel();
        panelHome2 = new javax.swing.JPanel();
        btnhome2 = new javax.swing.JLabel();
        panelHome3 = new javax.swing.JPanel();
        btnhome3 = new javax.swing.JLabel();
        panelHome6 = new javax.swing.JPanel();
        btnhome6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_studentdata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome5.setBackground(new java.awt.Color(0, 102, 102));
        panelHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome5.setForeground(new java.awt.Color(255, 255, 255));
        panelHome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome5.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome5.setForeground(new java.awt.Color(255, 255, 255));
        btnhome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/back-button.png"))); // NOI18N
        btnhome5.setText("Back");
        btnhome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome5MouseExited(evt);
            }
        });
        panelHome5.add(btnhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, -1));

        panelsideBar.add(panelHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 330, 70));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome.setText("  Logout");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        panelHome.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome1.setBackground(new java.awt.Color(0, 102, 102));
        panelHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome1.setForeground(new java.awt.Color(255, 255, 255));
        panelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome1.setForeground(new java.awt.Color(255, 255, 255));
        btnhome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/home.png"))); // NOI18N
        btnhome1.setText("  HOME");
        btnhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome1MouseExited(evt);
            }
        });
        panelHome1.add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 330, 70));

        panelHome2.setBackground(new java.awt.Color(0, 102, 102));
        panelHome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome2.setForeground(new java.awt.Color(255, 255, 255));
        panelHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome2.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome2.setForeground(new java.awt.Color(255, 255, 255));
        btnhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/new-user.png"))); // NOI18N
        btnhome2.setText(" New Registration");
        btnhome2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome2MouseExited(evt);
            }
        });
        panelHome2.add(btnhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, -1));

        panelsideBar.add(panelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 330, 70));

        panelHome3.setBackground(new java.awt.Color(0, 102, 102));
        panelHome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome3.setForeground(new java.awt.Color(255, 255, 255));
        panelHome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome3.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome3.setForeground(new java.awt.Color(255, 255, 255));
        btnhome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/edit2.png"))); // NOI18N
        btnhome3.setText("Edit Course");
        btnhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome3MouseExited(evt);
            }
        });
        panelHome3.add(btnhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, -1));

        panelsideBar.add(panelHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 330, 70));

        panelHome6.setBackground(new java.awt.Color(0, 102, 102));
        panelHome6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome6.setForeground(new java.awt.Color(255, 255, 255));
        panelHome6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome6.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome6.setForeground(new java.awt.Color(255, 255, 255));
        btnhome6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/view all record.png"))); // NOI18N
        btnhome6.setText("View All Record");
        btnhome6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome6MouseExited(evt);
            }
        });
        panelHome6.add(btnhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 280, -1));

        panelsideBar.add(panelHome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 1040));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search  Record");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Search String :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 410, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 410, 20));

        tbl_studentdata.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_studentdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reciept No.", "Enrollement No.", "Student Name", "Course Name", "Payment Mode", "Total Amount", "Remark"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_studentdata.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_studentdata);
        if (tbl_studentdata.getColumnModel().getColumnCount() > 0) {
            tbl_studentdata.getColumnModel().getColumn(0).setResizable(false);
            tbl_studentdata.getColumnModel().getColumn(1).setResizable(false);
            tbl_studentdata.getColumnModel().getColumn(2).setResizable(false);
            tbl_studentdata.getColumnModel().getColumn(3).setResizable(false);
            tbl_studentdata.getColumnModel().getColumn(4).setResizable(false);
            tbl_studentdata.getColumnModel().getColumn(5).setResizable(false);
            tbl_studentdata.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1420, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 1460, 1040));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhome5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseClicked
    Home home = new Home();
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnhome5MouseClicked

    private void btnhome5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseEntered
        Color clr=new Color(0,153,153);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btnhome5MouseEntered

    private void btnhome5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseExited
        Color clr=new Color(0,102,102);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btnhome5MouseExited

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        Color clr=new Color(0,102,102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseExited

    private void btnhome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseEntered
        Color clr=new Color(0,153,153);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btnhome1MouseEntered

    private void btnhome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseExited
        Color clr=new Color(0,102,102);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btnhome1MouseExited

    private void btnhome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseEntered
        Color clr=new Color(0,153,153);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btnhome2MouseEntered

    private void btnhome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseExited
        Color clr=new Color(0,102,102);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btnhome2MouseExited

    private void btnhome3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseEntered
        Color clr=new Color(0,153,153);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btnhome3MouseEntered

    private void btnhome3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseExited
        Color clr=new Color(0,102,102);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btnhome3MouseExited

    private void btnhome6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseEntered
        Color clr=new Color(0,153,153);
        panelHome6.setBackground(clr);
    }//GEN-LAST:event_btnhome6MouseEntered

    private void btnhome6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseExited
        Color clr=new Color(0,102,102);
        panelHome6.setBackground(clr);
    }//GEN-LAST:event_btnhome6MouseExited

    private void btnhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseClicked
AddFees addFees=new AddFees();
 addFees.setVisible(true);
 this.dispose();
                             
    }//GEN-LAST:event_btnhome2MouseClicked

    private void btnhome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseClicked
       Home a=new Home();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnhome1MouseClicked

    private void btnhome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseClicked
        EditCourse a=new EditCourse();
       a.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnhome3MouseClicked

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        String searchString = txt_search.getText();
        search(searchString);
    }//GEN-LAST:event_jPanel1KeyReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
String searchString = txt_search.getText();
      search(searchString);
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btnhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseClicked
Login_page a= new Login_page();
      a.setVisible(true);
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnhomeMouseClicked

    private void btnhome6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome6MouseClicked
ViewAllRecord a=new ViewAllRecord();
        a.setVisible(true);
        this.dispose();            // TODO add your handling code here:
    }//GEN-LAST:event_btnhome6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnhome1;
    private javax.swing.JLabel btnhome2;
    private javax.swing.JLabel btnhome3;
    private javax.swing.JLabel btnhome5;
    private javax.swing.JLabel btnhome6;
    private java.util.List<college_fee_management.FeesDetails> feesDetailsList;
    private javax.persistence.Query feesDetailsQuery;
    private javax.persistence.EntityManager fees_managementPUEntityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome1;
    private javax.swing.JPanel panelHome2;
    private javax.swing.JPanel panelHome3;
    private javax.swing.JPanel panelHome5;
    private javax.swing.JPanel panelHome6;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JTable tbl_studentdata;
    public javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

}