/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_fee_management;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
   String fname,lname,uname,password,con_pass,contact_no;
    Date dob;
    int id=0;
    
    public Signup() {
        initComponents();
    }
    public int getId()
    {
        ResultSet rs=null;
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
     Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/fees_management","root","root");
     String sql="select max(id)from signup";
     Statement st=con.createStatement();
     rs= st.executeQuery(sql);
     while (rs.next())
     {
         
         id=rs.getInt(1);
         id++;
     }
    } catch (ClassNotFoundException | SQLException e)
    {
    }
        return id;
    }
        
        
    boolean validation()
    {
    
    
    fname=txt_firstname.getText();
    lname=txt_lastname.getText();
    uname=txt_username.getText();
    password=txt_password.getText();
    con_pass=txt_con_pass.getText();
    contact_no=txt_contact.getText();
    dob1=txt_dob1.getDate();
   
   if (fname.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Enter First Name");
   return false;
    }
   if (lname.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Enter Last Name");
   return false;
    }
   if (uname.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Enter Username");
   return false;
    }
   if (password.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Enter Password");
   return false;
    }
   if (con_pass.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Confirm the Password");
   return false;
    }
   if (dob.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Enter D.O.B.");
   return false;
    }
    if (contact_no.equals(""))
   {
   JOptionPane.showMessageDialog(this,"Please Enter Contact No.");
   return false;
    }
    if(password.length()<8)
    {
    lbl_password_error.setText("Password should be 8 digits");
    }
    if(!password.equals(con_pass))
    {
     JOptionPane.showMessageDialog(this,"Password not matched");
     return false;
    }
     return true;
   
   
   
    }
    public void checkPassword()
    {
         password=txt_password.getText();
    if(password.length()<8)
        
    {
        lbl_password_error.setText("Password should be 8 digits");
    }
    else
    {
            lbl_password_error.setText("");

    }
    }
     public void checkContactNo()
    {
         contact_no=txt_contact.getText();
    if(contact_no.length()==10)
        
    {
        lbl_contact_error.setText("");
    }
    else
    {
            lbl_contact_error.setText("Contact No. should be 10 digits");
    }
    }
     void insertDetails()
     {
         SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
       String  mydob=format.format(dob);
     try
     {
     Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
     Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/fees_management","root","root");
     String sql="insert into signup values(?,?,?,?,?,?,?)";
     PreparedStatement stmt=con.prepareStatement(sql);
     stmt.setInt(1,getId());
     stmt.setString(2,fname);
     stmt.setString(3,lname);
     stmt.setString(4,uname);
     stmt.setString(5,password);
     stmt.setString(6,mydob);
     stmt.setString(7,contact_no);
     int i=stmt.executeUpdate();
     if(i>0)
     {
         JOptionPane.showMessageDialog(this,"record inserted");
     }
     else
     {
         JOptionPane.showMessageDialog(this,"record not inserted");
     }
     }
     
     catch (HeadlessException | ClassNotFoundException | SQLException e)
     {
     }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_signup = new javax.swing.JButton();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_con_pass = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();
        lbl_password_error = new javax.swing.JLabel();
        lbl_contact_error = new javax.swing.JLabel();
        dob1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/new-user.png"))); // NOI18N
        jLabel1.setText(" SignUp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/20230215_212050.jpg"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 120));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contact No. :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("D.O.B. :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, 30));

        btn_login.setBackground(new java.awt.Color(51, 51, 51));
        btn_login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/login.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 140, 50));

        btn_signup.setBackground(new java.awt.Color(51, 51, 51));
        btn_signup.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/signup.png"))); // NOI18N
        btn_signup.setText(" SignUp");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 140, 50));

        txt_firstname.setBackground(new java.awt.Color(0, 102, 102));
        txt_firstname.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        txt_firstname.setForeground(new java.awt.Color(255, 255, 255));
        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 170, 40));

        txt_lastname.setBackground(new java.awt.Color(0, 102, 102));
        txt_lastname.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        txt_lastname.setForeground(new java.awt.Color(255, 255, 255));
        txt_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 170, 40));

        txt_username.setBackground(new java.awt.Color(0, 102, 102));
        txt_username.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 170, 40));

        txt_contact.setBackground(new java.awt.Color(0, 102, 102));
        txt_contact.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contactKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contactKeyReleased(evt);
            }
        });
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 170, 40));

        txt_con_pass.setBackground(new java.awt.Color(0, 102, 102));
        txt_con_pass.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_con_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_con_passActionPerformed(evt);
            }
        });
        jPanel2.add(txt_con_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 170, 40));

        txt_password.setBackground(new java.awt.Color(0, 102, 102));
        txt_password.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 170, 40));

        lbl_password_error.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_password_error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_password_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 270, 30));

        lbl_contact_error.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lbl_contact_error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lbl_contact_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 260, 30));

        dob1.setBackground(new java.awt.Color(0, 51, 51));
        dob1.setForeground(new java.awt.Color(255, 255, 255));
        dob1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/20230215_212050.jpg"))); // NOI18N
        dob1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.lightGray));
        jPanel2.add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 580));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 790, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
if(validation())
{
    insertDetails();
}
    }//GEN-LAST:event_btn_signupActionPerformed

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastnameActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
 checkPassword();
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
   checkPassword();
    }//GEN-LAST:event_txt_passwordKeyReleased

    private void txt_contactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyPressed
  checkContactNo();
    }//GEN-LAST:event_txt_contactKeyPressed

    private void txt_dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dobKeyPressed
 
    }//GEN-LAST:event_txt_dobKeyPressed

    private void txt_contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyReleased
        checkContactNo();
    }//GEN-LAST:event_txt_contactKeyReleased

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        Login_page a=new Login_page();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_loginMouseClicked

    private void txt_con_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_con_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_con_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel dob1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_contact_error;
    private javax.swing.JLabel lbl_password_error;
    private javax.swing.JPasswordField txt_con_pass;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private static class txt_dob1 {

        private static JLabel getDate() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txt_dob1() {
        }
    }
}
