/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_fee_management;

import java.awt.Color;

/**
 *
 * @author Dell
 */
public class ViewAllRecord extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllRecord
     */
    public ViewAllRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        fees_managementPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("fees_managementPU").createEntityManager();
        feesDetailsQuery = java.beans.Beans.isDesignTime() ? null : fees_managementPUEntityManager.createQuery("SELECT f FROM FeesDetails f");
        feesDetailsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : feesDetailsQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelsideBar = new javax.swing.JPanel();
        panelHome5 = new javax.swing.JPanel();
        btnhome5 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnhome = new javax.swing.JLabel();
        panelHome1 = new javax.swing.JPanel();
        btnhome1 = new javax.swing.JLabel();
        panelHome2 = new javax.swing.JPanel();
        btnhome2 = new javax.swing.JLabel();
        panelHome3 = new javax.swing.JPanel();
        btnhome3 = new javax.swing.JLabel();
        panelHome4 = new javax.swing.JPanel();
        btnhome4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, feesDetailsList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${recieptNo}"));
        columnBinding.setColumnName("Reciept No");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rollNo}"));
        columnBinding.setColumnName("Roll No");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${studentName}"));
        columnBinding.setColumnName("Student Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${courseName}"));
        columnBinding.setColumnName("Course Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalAmount}"));
        columnBinding.setColumnName("Total Amount");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${paymentMode}"));
        columnBinding.setColumnName("Payment Mode");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${remark}"));
        columnBinding.setColumnName("Remark");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 980, 860));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 440, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 1130, 1010));

        panelsideBar.setBackground(new java.awt.Color(0, 102, 102));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome5.setBackground(new java.awt.Color(0, 102, 102));
        panelHome5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome5.setForeground(new java.awt.Color(255, 255, 255));
        panelHome5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome5.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome5.setForeground(new java.awt.Color(255, 255, 255));
        btnhome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/back-button.png"))); // NOI18N
        btnhome5.setText("Back");
        btnhome5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome5MouseExited(evt);
            }
        });
        panelHome5.add(btnhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 280, -1));

        panelsideBar.add(panelHome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 330, 70));

        panelHome.setBackground(new java.awt.Color(0, 102, 102));
        panelHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/logout.png"))); // NOI18N
        btnhome.setText("  Logout");
        btnhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomeMouseExited(evt);
            }
        });
        panelHome.add(btnhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 330, 70));

        panelHome1.setBackground(new java.awt.Color(0, 102, 102));
        panelHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome1.setForeground(new java.awt.Color(255, 255, 255));
        panelHome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome1.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome1.setForeground(new java.awt.Color(255, 255, 255));
        btnhome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/home.png"))); // NOI18N
        btnhome1.setText("  HOME");
        btnhome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome1MouseExited(evt);
            }
        });
        panelHome1.add(btnhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 330, 70));

        panelHome2.setBackground(new java.awt.Color(0, 102, 102));
        panelHome2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome2.setForeground(new java.awt.Color(255, 255, 255));
        panelHome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome2.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome2.setForeground(new java.awt.Color(255, 255, 255));
        btnhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/search2.png"))); // NOI18N
        btnhome2.setText("Search Record");
        btnhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome2MouseExited(evt);
            }
        });
        panelHome2.add(btnhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, -1));

        panelsideBar.add(panelHome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 330, 70));

        panelHome3.setBackground(new java.awt.Color(0, 102, 102));
        panelHome3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome3.setForeground(new java.awt.Color(255, 255, 255));
        panelHome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome3.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome3.setForeground(new java.awt.Color(255, 255, 255));
        btnhome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/new-user.png"))); // NOI18N
        btnhome3.setText("New Registration");
        btnhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome3MouseExited(evt);
            }
        });
        panelHome3.add(btnhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 320, -1));

        panelsideBar.add(panelHome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 330, 70));

        panelHome4.setBackground(new java.awt.Color(0, 102, 102));
        panelHome4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelHome4.setForeground(new java.awt.Color(255, 255, 255));
        panelHome4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome4.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        btnhome4.setForeground(new java.awt.Color(255, 255, 255));
        btnhome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/college_fee_management/images/list_1.png"))); // NOI18N
        btnhome4.setText("Edit Course");
        btnhome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhome4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhome4MouseExited(evt);
            }
        });
        panelHome4.add(btnhome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 280, -1));

        panelsideBar.add(panelHome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 330, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 1010));

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1688, 1054));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhome4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome4MouseExited
        Color clr=new Color(0,102,102);
        panelHome4.setBackground(clr);
    }//GEN-LAST:event_btnhome4MouseExited

    private void btnhome4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome4MouseEntered
        Color clr=new Color(0,153,153);
        panelHome4.setBackground(clr);
    }//GEN-LAST:event_btnhome4MouseEntered

    private void btnhome3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseExited
        Color clr=new Color(0,102,102);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btnhome3MouseExited

    private void btnhome3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseEntered
        Color clr=new Color(0,153,153);
        panelHome3.setBackground(clr);
    }//GEN-LAST:event_btnhome3MouseEntered

    private void btnhome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseClicked
        AddFees a=new AddFees();
        a.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome3MouseClicked

    private void btnhome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseExited
        Color clr=new Color(0,102,102);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btnhome2MouseExited

    private void btnhome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseEntered
        Color clr=new Color(0,153,153);
        panelHome2.setBackground(clr);
    }//GEN-LAST:event_btnhome2MouseEntered

    private void btnhome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseExited
        Color clr=new Color(0,102,102);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btnhome1MouseExited

    private void btnhome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseEntered
        Color clr=new Color(0,153,153);
        panelHome1.setBackground(clr);
    }//GEN-LAST:event_btnhome1MouseEntered

    private void btnhome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome1MouseClicked
        Home a=new Home();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnhome1MouseClicked

    private void btnhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseExited
        Color clr=new Color(0,102,102);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseExited

    private void btnhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomeMouseEntered
        Color clr=new Color(0,153,153);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnhomeMouseEntered

    private void btnhome5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseExited
        Color clr=new Color(0,102,102);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btnhome5MouseExited

    private void btnhome5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseEntered
        Color clr=new Color(0,153,153);
        panelHome5.setBackground(clr);
    }//GEN-LAST:event_btnhome5MouseEntered

    private void btnhome5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome5MouseClicked

    }//GEN-LAST:event_btnhome5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnhome;
    private javax.swing.JLabel btnhome1;
    private javax.swing.JLabel btnhome2;
    private javax.swing.JLabel btnhome3;
    private javax.swing.JLabel btnhome4;
    private javax.swing.JLabel btnhome5;
    private java.util.List<college_fee_management.FeesDetails> feesDetailsList;
    private javax.persistence.Query feesDetailsQuery;
    private javax.persistence.EntityManager fees_managementPUEntityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelHome1;
    private javax.swing.JPanel panelHome2;
    private javax.swing.JPanel panelHome3;
    private javax.swing.JPanel panelHome4;
    private javax.swing.JPanel panelHome5;
    private javax.swing.JPanel panelsideBar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
